# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import atom_pb2 as atom__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in atom_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AtomNodeStub(object):
    """Minimal node-to-node message contract
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/atom.AtomNode/SendMessage',
                request_serializer=atom__pb2.AtomMessage.SerializeToString,
                response_deserializer=atom__pb2.Ack.FromString,
                _registered_method=True)
        self.StreamMessages = channel.stream_stream(
                '/atom.AtomNode/StreamMessages',
                request_serializer=atom__pb2.AtomMessage.SerializeToString,
                response_deserializer=atom__pb2.AtomAck.FromString,
                _registered_method=True)


class AtomNodeServicer(object):
    """Minimal node-to-node message contract
    """

    def SendMessage(self, request, context):
        """Unary send — fire-and-wait ack
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMessages(self, request_iterator, context):
        """Streaming — for high-throughput feeds
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AtomNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=atom__pb2.AtomMessage.FromString,
                    response_serializer=atom__pb2.Ack.SerializeToString,
            ),
            'StreamMessages': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamMessages,
                    request_deserializer=atom__pb2.AtomMessage.FromString,
                    response_serializer=atom__pb2.AtomAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'atom.AtomNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('atom.AtomNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AtomNode(object):
    """Minimal node-to-node message contract
    """

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atom.AtomNode/SendMessage',
            atom__pb2.AtomMessage.SerializeToString,
            atom__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMessages(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/atom.AtomNode/StreamMessages',
            atom__pb2.AtomMessage.SerializeToString,
            atom__pb2.AtomAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
