# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: atom.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'atom.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\natom.proto\x12\x04\x61tom\"\xc6\x01\n\x0b\x41tomMessage\x12\x0e\n\x06msg_id\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0e\n\x06target\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x0b\n\x03ttl\x18\x06 \x01(\x05\x12)\n\x04meta\x18\x07 \x03(\x0b\x32\x1b.atom.AtomMessage.MetaEntry\x1a+\n\tMetaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"=\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0e\n\x06msg_id\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x0b\n\x03seq\x18\x04 \x01(\x03\"G\n\x07\x41tomAck\x12\x0e\n\x06msg_id\x18\x01 \x01(\t\x12\n\n\x02ok\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x11\n\tserver_ts\x18\x04 \x01(\x03\x32o\n\x08\x41tomNode\x12+\n\x0bSendMessage\x12\x11.atom.AtomMessage\x1a\t.atom.Ack\x12\x36\n\x0eStreamMessages\x12\x11.atom.AtomMessage\x1a\r.atom.AtomAck(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'atom_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ATOMMESSAGE_METAENTRY']._loaded_options = None
  _globals['_ATOMMESSAGE_METAENTRY']._serialized_options = b'8\001'
  _globals['_ATOMMESSAGE']._serialized_start=21
  _globals['_ATOMMESSAGE']._serialized_end=219
  _globals['_ATOMMESSAGE_METAENTRY']._serialized_start=176
  _globals['_ATOMMESSAGE_METAENTRY']._serialized_end=219
  _globals['_ACK']._serialized_start=221
  _globals['_ACK']._serialized_end=282
  _globals['_ATOMACK']._serialized_start=284
  _globals['_ATOMACK']._serialized_end=355
  _globals['_ATOMNODE']._serialized_start=357
  _globals['_ATOMNODE']._serialized_end=468
# @@protoc_insertion_point(module_scope)
