"""
DRL v1 — DRLMessage envelope.
All cross-node messages MUST pass through DRLMessage.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any
import time
import uuid


@dataclass(frozen=True, slots=True)
class DRLMessage:
    """
    Immutable envelope for all messages passing through DRL.

    distortion flags are set by DRL layer itself (NOT by sender).
    These flags tell the receiver WHAT distortion was applied,
    so the receiver's CCL layer can reason about it.

    Attributes
    ----------
    msg_id : str
        Unique identifier — generated by DRL on ingress, not by sender.
        Enables deduplication tracking.
    sender : str
        Logical sender node ID.
    receiver : str
        Logical receiver node ID (or "BROADCAST").
    payload : Any
        Opaque payload for CCL/F2 layer. DRL never inspects it.
    lamport_ts : int
        Logical timestamp at send time (from DRLClock).
    physical_ts : float
        Wall-clock seconds when DRL applied distortion.
    delivery_delay : float
        Seconds the message spent in DRL transit buffer.
        0 = delivered immediately (no artificial delay).
    dropped : bool
        True = message was probabilistically dropped.
        receiver = None in this case.
    duplicated : bool
        True = this is a duplicate injected by DRL.
        Original msg_id preserved.
    reordered : bool
        True = message arrived out-of-order relative to
        sender's original sequence.
    path : tuple[str, ...]
        Ordered list of node IDs the message has transited through.
        Used by PartitionModel to detect routing loops.
    """

    msg_id: str = field(default_factory=lambda: uuid.uuid4().hex[:16])
    sender: str = ""
    receiver: str = ""
    payload: Any = None
    lamport_ts: int = 0
    physical_ts: float = field(default_factory=time.time)
    delivery_delay: float = 0.0
    dropped: bool = False
    duplicated: bool = False
    reordered: bool = False
    path: tuple[str, ...] = field(default_factory=tuple)

    def with_distortion(
        self,
        *,
        delay: float = 0.0,
        dup: bool = False,
        reorder: bool = False,
        dropped: bool = False,
    ) -> DRLMessage:
        """Create a new DRLMessage with distortion flags set."""
        return DRLMessage(
            msg_id=self.msg_id,
            sender=self.sender,
            receiver=self.receiver,
            payload=self.payload,
            lamport_ts=self.lamport_ts,
            physical_ts=self.physical_ts,
            delivery_delay=delay,
            dropped=dropped,
            duplicated=dup,
            reordered=reorder,
            path=self.path,
        )

    def with_receiver(self, receiver: str) -> DRLMessage:
        """Create a new message addressed to a different receiver."""
        return DRLMessage(
            msg_id=self.msg_id,
            sender=self.sender,
            receiver=receiver,
            payload=self.payload,
            lamport_ts=self.lamport_ts,
            physical_ts=self.physical_ts,
            delivery_delay=self.delivery_delay,
            dropped=self.dropped,
            duplicated=self.duplicated,
            reordered=self.reordered,
            path=self.path,
        )

    def is_broadcast(self) -> bool:
        return self.receiver == "BROADCAST"
