# ansible-lint config
version: "6.22.0"
exclude_paths:
  - .venv/
  - "**/*.bak"
  mock_modules:
    - community.docker
  mock_roles:
    - ansible的角色
  skip_list:
    - yaml
    - name[casing]
  warning: false
  warn_list:
    - name[casing]
    - yaml
  keyed_values: false
