"""Planner for SDLC OS Healer Engine."""

from typing import Optional
from dataclasses import dataclass


@dataclass
class HealerDecision:
    """
    Result of healer's evaluation.
    
    Attributes:
        should_heal: True if healing is recommended
        block_reason: If should_heal=False, why it was blocked
        confidence: 0.0-1.0 confidence in the decision
        recommended_plans: List of repair plans (may be empty)
    """
    should_heal: bool
    block_reason: Optional[str]
    confidence: float
    recommended_plans: list


class HealerPlanner:
    """
    Determines whether healing should proceed.
    
    Constraints:
    - Always requires audit results before deciding
    - risk_score > 0.6 blocks healing
    - Only generates plans (does not execute)
    - Requires explicit approval for all plans
    """
    
    def __init__(self, risk_threshold: float = 0.6):
        self.risk_threshold = risk_threshold
    
    def evaluate(
        self,
        audit_report: dict,
        risk_score: float,
        anomalies: list
    ) -> HealerDecision:
        """
        Evaluate whether healing should proceed.
        
        Args:
            audit_report: System audit results
            risk_score: Computed system risk score
            anomalies: List of detected anomalies
        
        Returns:
            HealerDecision with recommendation
        """
        # Check risk gate
        if risk_score > self.risk_threshold:
            return HealerDecision(
                should_heal=False,
                block_reason=f"Risk score {risk_score:.2f} exceeds threshold {self.risk_threshold}",
                confidence=0.95,
                recommended_plans=[]
            )
        
        # Check audit validity
        dag_valid = audit_report.get('dag_valid', False)
        cycle_detected = audit_report.get('cycle_detected', False)
        
        if not dag_valid or cycle_detected:
            return HealerDecision(
                should_heal=False,
                block_reason="DAG integrity compromised - cycles detected or invalid structure",
                confidence=0.90,
                recommended_plans=[]
            )
        
        # Check anomalies exist
        if not anomalies:
            return HealerDecision(
                should_heal=False,
                block_reason="No anomalies detected - nothing to heal",
                confidence=0.80,
                recommended_plans=[]
            )
        
        # Healing can proceed
        return HealerDecision(
            should_heal=True,
            block_reason=None,
            confidence=0.85,
            recommended_plans=[]  # Plans generated by PatchGenerator
        )
    
    def get_healer_status(self, decision: HealerDecision) -> str:
        """Return healer status string."""
        return "enabled" if decision.should_heal else "disabled"