# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import atom_os_pb2 as proto_dot_atom__os__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/atom_os_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeRPCStub(object):
    """── Service Definition ────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/atom.NodeRPC/Ping',
                request_serializer=proto_dot_atom__os__pb2.PingRequest.SerializeToString,
                response_deserializer=proto_dot_atom__os__pb2.Pong.FromString,
                _registered_method=True)
        self.Forward = channel.unary_unary(
                '/atom.NodeRPC/Forward',
                request_serializer=proto_dot_atom__os__pb2.ForwardRequest.SerializeToString,
                response_deserializer=proto_dot_atom__os__pb2.ForwardResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/atom.NodeRPC/StreamEvents',
                request_serializer=proto_dot_atom__os__pb2.EventRequest.SerializeToString,
                response_deserializer=proto_dot_atom__os__pb2.Event.FromString,
                _registered_method=True)
        self.RequestVote = channel.unary_unary(
                '/atom.NodeRPC/RequestVote',
                request_serializer=proto_dot_atom__os__pb2.VoteRequest.SerializeToString,
                response_deserializer=proto_dot_atom__os__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.AppendEntries = channel.unary_unary(
                '/atom.NodeRPC/AppendEntries',
                request_serializer=proto_dot_atom__os__pb2.AppendEntriesRequest.SerializeToString,
                response_deserializer=proto_dot_atom__os__pb2.AppendEntriesResponse.FromString,
                _registered_method=True)


class NodeRPCServicer(object):
    """── Service Definition ────────────────────────────────────────────────────
    """

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Forward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=proto_dot_atom__os__pb2.PingRequest.FromString,
                    response_serializer=proto_dot_atom__os__pb2.Pong.SerializeToString,
            ),
            'Forward': grpc.unary_unary_rpc_method_handler(
                    servicer.Forward,
                    request_deserializer=proto_dot_atom__os__pb2.ForwardRequest.FromString,
                    response_serializer=proto_dot_atom__os__pb2.ForwardResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=proto_dot_atom__os__pb2.EventRequest.FromString,
                    response_serializer=proto_dot_atom__os__pb2.Event.SerializeToString,
            ),
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=proto_dot_atom__os__pb2.VoteRequest.FromString,
                    response_serializer=proto_dot_atom__os__pb2.VoteResponse.SerializeToString,
            ),
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=proto_dot_atom__os__pb2.AppendEntriesRequest.FromString,
                    response_serializer=proto_dot_atom__os__pb2.AppendEntriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'atom.NodeRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('atom.NodeRPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeRPC(object):
    """── Service Definition ────────────────────────────────────────────────────
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atom.NodeRPC/Ping',
            proto_dot_atom__os__pb2.PingRequest.SerializeToString,
            proto_dot_atom__os__pb2.Pong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Forward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atom.NodeRPC/Forward',
            proto_dot_atom__os__pb2.ForwardRequest.SerializeToString,
            proto_dot_atom__os__pb2.ForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/atom.NodeRPC/StreamEvents',
            proto_dot_atom__os__pb2.EventRequest.SerializeToString,
            proto_dot_atom__os__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atom.NodeRPC/RequestVote',
            proto_dot_atom__os__pb2.VoteRequest.SerializeToString,
            proto_dot_atom__os__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atom.NodeRPC/AppendEntries',
            proto_dot_atom__os__pb2.AppendEntriesRequest.SerializeToString,
            proto_dot_atom__os__pb2.AppendEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
