# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/atom_os.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/atom_os.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/atom_os.proto\x12\x04\x61tom\"1\n\x04Pong\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x03\x12\n\n\x02ok\x18\x03 \x01(\x08\"6\n\x0e\x46orwardRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x13\n\x0borigin_node\x18\x02 \x01(\t\"2\n\x0f\x46orwardResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06result\x18\x02 \x01(\t\"3\n\x05\x45vent\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0b\n\x03seq\x18\x02 \x01(\x03\x12\x0c\n\x04type\x18\x03 \x01(\t\"a\n\tSBARecord\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\tinvariant\x18\x02 \x01(\t\x12\x0c\n\x04held\x18\x03 \x01(\x08\x12\x0c\n\x04term\x18\x04 \x01(\x03\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\"`\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x03\x12\x15\n\rlast_log_term\x18\x04 \x01(\x03\"2\n\x0cVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"\x8e\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x03\x12\x15\n\rprev_log_term\x18\x04 \x01(\x03\x12\x0f\n\x07\x65ntries\x18\x05 \x03(\x0c\x12\x15\n\rleader_commit\x18\x06 \x01(\x03\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0f\n\x07success\x18\x02 \x01(\x08\"\r\n\x0bPingRequest\"\x0e\n\x0c\x45ventRequest2\x9b\x02\n\x07NodeRPC\x12%\n\x04Ping\x12\x11.atom.PingRequest\x1a\n.atom.Pong\x12\x36\n\x07\x46orward\x12\x14.atom.ForwardRequest\x1a\x15.atom.ForwardResponse\x12\x31\n\x0cStreamEvents\x12\x12.atom.EventRequest\x1a\x0b.atom.Event0\x01\x12\x34\n\x0bRequestVote\x12\x11.atom.VoteRequest\x1a\x12.atom.VoteResponse\x12H\n\rAppendEntries\x12\x1a.atom.AppendEntriesRequest\x1a\x1b.atom.AppendEntriesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.atom_os_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PONG']._serialized_start=29
  _globals['_PONG']._serialized_end=78
  _globals['_FORWARDREQUEST']._serialized_start=80
  _globals['_FORWARDREQUEST']._serialized_end=134
  _globals['_FORWARDRESPONSE']._serialized_start=136
  _globals['_FORWARDRESPONSE']._serialized_end=186
  _globals['_EVENT']._serialized_start=188
  _globals['_EVENT']._serialized_end=239
  _globals['_SBARECORD']._serialized_start=241
  _globals['_SBARECORD']._serialized_end=338
  _globals['_VOTEREQUEST']._serialized_start=340
  _globals['_VOTEREQUEST']._serialized_end=436
  _globals['_VOTERESPONSE']._serialized_start=438
  _globals['_VOTERESPONSE']._serialized_end=488
  _globals['_APPENDENTRIESREQUEST']._serialized_start=491
  _globals['_APPENDENTRIESREQUEST']._serialized_end=633
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=635
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=689
  _globals['_PINGREQUEST']._serialized_start=691
  _globals['_PINGREQUEST']._serialized_end=704
  _globals['_EVENTREQUEST']._serialized_start=706
  _globals['_EVENTREQUEST']._serialized_end=720
  _globals['_NODERPC']._serialized_start=723
  _globals['_NODERPC']._serialized_end=1006
# @@protoc_insertion_point(module_scope)
