# ============================================================
# Module: network — MikroTik VLAN + WireGuard config
# ============================================================
# Generates RouterOS script for MikroTik hEX S
# And WireGuard interface configs for mesh peers
# ============================================================

resource "local_file" "mikrotik_script" {
  filename = "${path.module}/mikrotik_setup.rsc"
  content  = <<-EOT
# ============================================================
# MikroTik RouterOS — VLAN + WireGuard Mesh
# Generated by: home-cluster-iac/terraform/modules/network
# ============================================================

# ── VLAN interface setup ─────────────────────────────────────
/interface/vlan
%{ for name, vlan in vlan_segments ~}
add name=vlan${vlan.id}-${name} vlan-id=${vlan.id} interface=bridge
%{ endfor ~}

# ── VLAN IP addressing ───────────────────────────────────────
/ip address
%{ for name, vlan in vlan_segments ~}
add address=${vlan.subnet}/24 interface="vlan${vlan.id}-${name}" comment="VLAN ${vlan.id} — ${vlan.desc}"
%{ endfor ~}

# ── WireGuard mesh interface (Mesh VPN L0) ───────────────────
/interface/wireguard
add name=wg-mesh listen-port=${wireguard_port} mtu=1420

# WireGuard peers (mesh participants)
/interface/wireguard/peers
# Home RTX node
add interface=wg-mesh public-key="${home_wg_pubkey}" endpoint-address=${home_endpoint} endpoint-port=${wireguard_port} persistent-keepalive=25 allowed-address=${mesh_subnet}
# Edge RK node
add interface=wg-mesh public-key="${edge_wg_pubkey}" endpoint-address=${edge_endpoint} endpoint-port=${wireguard_port} persistent-keepalive=25 allowed-address=${mesh_subnet}

# Mesh IP on router (router is also a mesh node)
add address=10.200.0.1/16 interface=wg-mesh comment="Mesh VPN gateway"

# ── Routing ──────────────────────────────────────────────────
# Default route
/ip route
add dst-address=0.0.0.0/0 gateway=${upstream_gateway} comment="Upstream default"

# Inter-VLAN routing (if bridge is used)
/ip route
add dst-address=${mesh_vpn_subnet} gateway=wg-mesh comment="Mesh VPN routes"

# ── Firewall — basic security ───────────────────────────────
/ip firewall filter
add chain=input action=accept connection-state=established,related comment="Allow established"
add chain=input action=accept protocol=icmp comment="Allow ICMP"
add chain=input action=drop chain=input in-interface=!bridge comment="Drop non-bridge input"

# ── DHCP server per VLAN (optional) ──────────────────────────
%{ for name, vlan in vlan_segments ~}
# DHCP for VLAN ${vlan.id} — ${vlan.desc}
/ip pool
add name=pool-${name} ranges=${cidrsubnet(vlan.subnet, 24, 2)}-${cidrsubnet(vlan.subnet, 24, 254)}
/ip dhcp-server
add address-pool=pool-${name} interface="vlan${vlan.id}-${name}" name=dhcp-${name}
/ip dhcp-server network
add address=${vlan.subnet}/24 dns-server=${dns_server} gateway=${cidrhost(vlan.subnet, 1)}
%{ endfor ~}

EOT
}

resource "local_file" "wireguard_home_conf" {
  filename = "${path.module}/wg-home.conf"
  content  = <<-EOT
# ============================================================
# WireGuard — Home Node (RTX 3060)
# ============================================================
[Interface]
Address    = 10.200.0.10/16
PrivateKey = ${home_private_key}
ListenPort = ${wireguard_port}
MTU        = 1420

# Edge node peer
[Peer]
PublicKey  = ${edge_wg_pubkey}
Endpoint   = ${edge_endpoint}:${wireguard_port}
AllowedIPs = 10.200.0.0/16
PersistentKeepalive = 25

# Route all cluster traffic
EOT
}

resource "local_file" "wireguard_edge_conf" {
  filename = "${path.module}/wg-edge.conf"
  content  = <<-EOT
# ============================================================
# WireGuard — Edge Node (RK3576)
# ============================================================
[Interface]
Address    = 10.200.0.11/16
PrivateKey = ${edge_private_key}
ListenPort = ${wireguard_port}
MTU        = 1420

# Home node peer
[Peer]
PublicKey  = ${home_wg_pubkey}
Endpoint   = ${home_endpoint}:${wireguard_port}
AllowedIPs = 10.200.0.0/16
PersistentKeepalive = 25
EOT
}

# Null resources for local variable interpolation
resource "null_resource" "mesh_subnet_calc" {
  triggers = { mesh_subnet = var.mesh_vpn_subnet }
}

resource "null_resource" "edge_wg_pubkey" {
  triggers = { pubkey = var.edge_wg_pubkey }
}
